//! C ABI exports and the optional CUDA synchronization driver.
//!
//! This crate is the integration boundary of the FLARE workspace:
//!
//! - [`c_abi`] exposes the vector index and the radix attention engine as
//!   plain C functions over opaque handles, with a generated C header at
//!   `include/flare.h` (regenerated by the build script through cbindgen);
//! - the [`cuda`] module (behind `feature = "cuda"`) implements the
//!   `flare_core::sync::gpu::GpuSyncDriver` contract for
//!   CUDA deployments. The runtime is loaded dynamically, so building this
//!   crate never requires a CUDA toolkit; a missing runtime surfaces as
//!   `flare_core::error::FlareError::GpuDriverUnavailable`.
//!
//! The crate is `#![no_std]`: the exported functions never allocate on the
//! C side, and every handle owns its heap-backed engine internally.
//!
//! The C API returns a status code `flare_status_t` where `0` means success
//! and positive values map onto `flare_core::error::FlareError` variants
//! (see `c_abi::flare_status`).
extern crate alloc;

/// C ABI exports over opaque engine handles.
#[allow(unsafe_code)] // The FFI boundary dereferences raw handles by design.
pub mod c_abi;

/// Optional CUDA synchronization driver (feature `cuda`).
#[cfg(feature = "cuda")]
#[allow(unsafe_code)] // Dynamic symbol loading is inherently unsafe by design.
pub mod cuda;
